from psycopg import Error

from app.core.logger import get_logger
from app.db.connection import get_connection
from app.db.errors import DatabaseOperationError

logger = get_logger(__name__)


def init_db() -> None:
    """Initialize application tables in PostgreSQL."""
    try:
        with get_connection() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS videos (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    youtube_url TEXT,
                    youtube_video_id TEXT,
                    title TEXT,
                    transcript TEXT,
                    status TEXT NOT NULL DEFAULT 'ready',
                    error_message TEXT,
                    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
                    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
                )
                """
            )
            conn.execute("ALTER TABLE videos ALTER COLUMN transcript DROP NOT NULL")
            conn.execute(
                """
                ALTER TABLE videos
                ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ready'
                """
            )
            conn.execute(
                """
                ALTER TABLE videos
                ADD COLUMN IF NOT EXISTS error_message TEXT
                """
            )
            conn.execute(
                """
                ALTER TABLE videos
                ADD COLUMN IF NOT EXISTS updated_at TEXT NOT NULL
                DEFAULT (CURRENT_TIMESTAMP::text)
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS chat_sessions (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    video_id INTEGER REFERENCES videos (id) ON DELETE SET NULL,
                    title TEXT,
                    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS messages (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    session_id INTEGER NOT NULL
                        REFERENCES chat_sessions (id) ON DELETE CASCADE,
                    role TEXT NOT NULL,
                    content TEXT NOT NULL,
                    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
                )
                """
            )
            conn.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS idx_videos_youtube_video_id
                ON videos (youtube_video_id)
                """
            )
            conn.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_videos_status
                ON videos (status)
                """
            )
            conn.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_chat_sessions_video_id
                ON chat_sessions (video_id)
                """
            )
            conn.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_messages_session_id
                ON messages (session_id)
                """
            )
        logger.info("Database initialized successfully")
    except Error as exc:
        raise DatabaseOperationError("Failed to initialize the database") from exc
